/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SecretaryView;

import View.StartScreen;
import hospitalapp.SystemDatabase;
import static hospitalapp.SystemDatabase.accountRequests;
import static hospitalapp.SystemDatabase.appointments;
import static hospitalapp.SystemDatabase.deletionRequests;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sbloxham2
 */
public class SecretaryHomepage extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryHomepage
     */
    public SecretaryHomepage() {
        initComponents();
        
        lblWelcomeMsg.setText("Welcome back " + SystemDatabase.findUser(SystemDatabase.getCurrentUserID()).getFirstName());
        
    }

    
    
    public static void checkNotifs(){
        
        boolean newAccounts = false;
        boolean newTerminationReqs = false;
        boolean newAppointmentReqs = false;
        boolean outOfMeds = false;
        
        
        
        for (int i = 0; i < SystemDatabase.accountRequests.size(); i++) 
        {
            newAccounts = true;
        }
        
        for (int i = 0; i < SystemDatabase.deletionRequests.size(); i++) 
        {
                 newTerminationReqs = true;   
        }
        
        for (int i = 0; i < SystemDatabase.appointments.size(); i++) 
        {
            
            if(SystemDatabase.appointments.get(i).getStatus().equals("pending"))
            {
                newAppointmentReqs = true;
            }
            }
        
        
        for (int i = 0; i < SystemDatabase.medicines.size(); i++) 
        {
            
            if(SystemDatabase.medicines.get(i).getStock() < 2)
            {
                outOfMeds = true;
            }
            }
        
        
        if(newAccounts == true)
        {
            showMessageDialog(null, "There are new patient account requests [Go to 'Approve Accounts' to verify them]");
        }
        
        if(newTerminationReqs == true)
        {
            showMessageDialog(null, "There are new account termination requests [Go to 'Approve Removal' to remove the accounts]");
        }
        
        if(newAppointmentReqs == true)
        {
            showMessageDialog(null, "There are new appointment requests [Go to 'Appointment Requests' to organise them]");
        }
        
        if(outOfMeds == true)
        {
            showMessageDialog(null, "The current stock of medicine is running low [Go to 'Order Medicine' to order more]");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogOut = new javax.swing.JButton();
        btnRemovePatients = new javax.swing.JButton();
        btnAppointmentRequests = new javax.swing.JButton();
        btnRemoval = new javax.swing.JButton();
        btnApproveAccounts = new javax.swing.JButton();
        lblWelcomeMsg = new javax.swing.JLabel();
        btnOrderMeds = new javax.swing.JButton();
        btnGiveMeds = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnRemovePatients.setText("Remove Patients");
        btnRemovePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePatientsActionPerformed(evt);
            }
        });

        btnAppointmentRequests.setText("Appointment Requests");
        btnAppointmentRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentRequestsActionPerformed(evt);
            }
        });

        btnRemoval.setText("Approve Removal");
        btnRemoval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovalActionPerformed(evt);
            }
        });

        btnApproveAccounts.setText("Approve Accounts");
        btnApproveAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveAccountsActionPerformed(evt);
            }
        });

        lblWelcomeMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMsg.setText("Welcome Back");

        btnOrderMeds.setText("Order Medicine");
        btnOrderMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMedsActionPerformed(evt);
            }
        });

        btnGiveMeds.setText("Give Medicines");
        btnGiveMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveMedsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblWelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApproveAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemovePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiveMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAppointmentRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoval, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApproveAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoval, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppointmentRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiveMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemovePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:

        new StartScreen().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnRemovePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePatientsActionPerformed
        // TODO add your handling code here:

        new RemovePatients().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRemovePatientsActionPerformed

    private void btnAppointmentRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentRequestsActionPerformed
        // TODO add your handling code here:

        new AppointmentRequests().setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_btnAppointmentRequestsActionPerformed

    private void btnRemovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovalActionPerformed
        // TODO add your handling code here:

        new AccountRemoval().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRemovalActionPerformed

    private void btnApproveAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveAccountsActionPerformed
        // TODO add your handling code here:

        
        new AccountApproval().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnApproveAccountsActionPerformed

    private void btnOrderMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMedsActionPerformed
        // TODO add your handling code here:
        
        new OrderMedicine().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnOrderMedsActionPerformed

    private void btnGiveMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveMedsActionPerformed
        // TODO add your handling code here:
        
         new GiveMedicine().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnGiveMedsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentRequests;
    private javax.swing.JButton btnApproveAccounts;
    private javax.swing.JButton btnGiveMeds;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOrderMeds;
    private javax.swing.JButton btnRemoval;
    private javax.swing.JButton btnRemovePatients;
    private javax.swing.JLabel lblWelcomeMsg;
    // End of variables declaration//GEN-END:variables
}
